Update enigma2.sh.in

diff --git a/tools/enigma2.sh.in b/tools/enigma2.sh.in
--- a/tools/enigma2.sh.in
+++ b/tools/enigma2.sh.in
@@ -5,8 +5,8 @@ exec_prefix=@exec_prefix@
 datarootdir=@datarootdir@
 
 if [ -d /home/root ]; then
+	cd /home/root
 	export HOME=/home/root
-	cd
 fi
 
 # any debuglevel passed?
@@ -41,6 +41,13 @@ while : ; do
 		@bindir@/enigma2_pre_start.sh
 	fi
 
+# Randomize timestamp if clock is not set
+RANDOMIZE1970=''
+time=`date +%Y` ;
+if [ "$time" = 1970 ]; then
+	RANDOMIZE1970="$(strings /dev/urandom | grep -o '[[:alnum:]]' | head -n 5 | tr -d '\n')"
+fi
+
 	# start enigma
 	sync
 # Set time format used to prefix each line in the debug logs.
@@ -48,116 +55,155 @@ DEBUGTIME=`sed -En 's|^config\.crash\.debugTimeFormat=(.+)$|\1|p' "@sysconfdir@/
 [ -n "${DEBUGTIME}" ] || DEBUGTIME="2"
 DEBUG_TIME="${DEBUGTIME}"
 
-if [ "$(grep -i config.crash.enabledebug=true /etc/enigma2/settings)" != "" ]; then
-		DEBUG_LVL='4'
-		RANDOMIZE1970=''
-		time=`date +%Y` ;
-		if [ "$time" = 1970 ]; then
-			RANDOMIZE1970="$(strings /dev/urandom | grep -o '[[:alnum:]]' | head -n 5 | tr -d '\n')"
-		fi
-		LOGFOLDER="/home/root/logs/"
-		if [ ! -d $LOGFOLDER ] ; then mkdir -p $LOGFOLDER; fi
-		if [ "$(grep config.crash.debugpath= /etc/enigma2/settings | sed 's/config.crash.debugpath=//g')" != "" -a -d "$(grep config.crash.debugpath= /etc/enigma2/settings | sed 's/config.crash.debugpath=//g')" ]; then
-			LOGFOLDER=$(grep config.crash.debugpath= /etc/enigma2/settings | sed 's/config.crash.debugpath=//g')
-		fi
-	LD_PRELOAD=$LIBS ENIGMA_DEBUG_LVL=$DEBUG_LVL ENIGMA_DEBUG_TIME="${DEBUG_TIME}" @bindir@/enigma2 &> ${LOGFOLDER}Enigma2-debug-$(date +%Y%m%d_%H-%M-%S)${RANDOMIZE1970}.log
-	else
-	LD_PRELOAD=$LIBS ENIGMA_DEBUG_LVL=$DEBUG_LVL ENIGMA_DEBUG_TIME="${DEBUG_TIME}" @bindir@/enigma2
+# Create and set log folder
+LOGFOLDER="/home/root/logs/"
+if [ ! -d $LOGFOLDER ] ; then mkdir -p $LOGFOLDER; fi
+if [ "$(grep config.crash.debug_path= /etc/enigma2/settings | sed 's/config.crash.debug_path=//g')" != "" -a -d "$(grep config.crash.debug_path= /etc/enigma2/settings | sed 's/config.crash.debug_path=//g')" ]; then
+	LOGFOLDER=$(grep config.crash.debug_path= /etc/enigma2/settings | sed 's/config.crash.debug_path=//g')
+fi
+
+# Enable and configure gstreamer debug log of category and level without color
+if [ "$(grep -i config.crash.gstdebug=true /etc/enigma2/settings)" != "" ]; then
+	GSTDEBUGCATEGORY="*"
+	GSTDEBUGLEVEL="INFO"
+	if [ "$(grep config.crash.gstdebugcategory= /etc/enigma2/settings | sed 's/config.crash.gstdebugcategory=//g')" != "" ]; then
+		GSTDEBUGCATEGORY=$(grep config.crash.gstdebugcategory= /etc/enigma2/settings | sed 's/config.crash.gstdebugcategory=//g')
 	fi
+	if [ "$(grep config.crash.gstdebuglevel= /etc/enigma2/settings | sed 's/config.crash.gstdebuglevel=//g')" != "" ]; then
+		GSTDEBUGLEVEL=$(grep config.crash.gstdebuglevel= /etc/enigma2/settings | sed 's/config.crash.gstdebuglevel=//g')
+	fi
+	export GST_DEBUG_FILE="${LOGFOLDER}$(date +%Y%m%d-%H%M%S)-gstreamer-debug.log"
+	export GST_DEBUG="${GSTDEBUGCATEGORY}:${GSTDEBUGLEVEL}"
+	export GST_DEBUG_NO_COLOR="1"
+fi
 
+# Enable and set gstreamer directory for pipeline graphs that are not created if directory is not set
+if [ "$(grep -i config.crash.gstdot=true /etc/enigma2/settings)" != "" ]; then
+	export GST_DEBUG_DUMP_DOT_DIR=${LOGFOLDER}
+fi
 
-	# enigma2 exit codes:
-	#
-	#  1 - halt
-	#  2 - reboot
-	#  4 - front processor upgrade
-	#  5 - install new settings
-	#  7 - manufacturer reset
-	# 42 - offline update
-	# 43 - restart for autoinstall
-	#
-	# >128 signal
+# Enable and configure gstreamer debug log of category and level without color
+if [ "$(grep -i config.crash.gstdebug=true /etc/enigma2/settings)" != "" ]; then
+	GSTDEBUGCATEGORY="*"
+	GSTDEBUGLEVEL="INFO"
+	if [ "$(grep config.crash.gstdebugcategory= /etc/enigma2/settings | sed 's/config.crash.gstdebugcategory=//g')" != "" ]; then
+		GSTDEBUGCATEGORY=$(grep config.crash.gstdebugcategory= /etc/enigma2/settings | sed 's/config.crash.gstdebugcategory=//g')
+	fi
+	if [ "$(grep config.crash.gstdebuglevel= /etc/enigma2/settings | sed 's/config.crash.gstdebuglevel=//g')" != "" ]; then
+		GSTDEBUGLEVEL=$(grep config.crash.gstdebuglevel= /etc/enigma2/settings | sed 's/config.crash.gstdebuglevel=//g')
+	fi
+	export GST_DEBUG_FILE="${LOGFOLDER}$(date +%Y%m%d-%H%M%S)-gstreamer-debug.log"
+	export GST_DEBUG="${GSTDEBUGCATEGORY}:${GSTDEBUGLEVEL}"
+	export GST_DEBUG_NO_COLOR="1"
+fi
 
-	ret=$?
-	case $ret in
-		1)
-			/sbin/halt
-			;;
-		2)
-			/sbin/reboot
-			;;
-		4)
-			/sbin/rmmod lcd
-			/usr/sbin/fpupgrade --upgrade 2>&1 | tee /home/root/fpupgrade.log
-			sleep 1;
-			/sbin/rmmod fp
-			/sbin/modprobe fp
-			/sbin/reboot
-			;;
-		5)
-			if ! grep -q config.misc.RestartUI /etc/enigma2/settings; then
-				echo "config.misc.RestartUI=true" >>/etc/enigma2/settings
+# Enable and set gstreamer directory for pipeline graphs that are not created if directory is not set
+if [ "$(grep -i config.crash.gstdot=true /etc/enigma2/settings)" != "" ]; then
+	export GST_DEBUG_DUMP_DOT_DIR=${LOGFOLDER}
+fi
+
+# Start enigma2 with or without debug
+if [ "$(grep -i config.crash.enabledebug=true /etc/enigma2/settings)" != "" ]; then
+	DEBUG_LVL='4'
+	LD_PRELOAD=$LIBS ENIGMA_DEBUG_LVL=$DEBUG_LVL ENIGMA_DEBUG_TIME="${DEBUG_TIME}" @bindir@/enigma2 &> ${LOGFOLDER}$(date +%Y%m%d-%H%M%S)-enigma2-debug.log
+else
+	LD_PRELOAD=$LIBS ENIGMA_DEBUG_LVL=$DEBUG_LVL ENIGMA_DEBUG_TIME="${DEBUG_TIME}" @bindir@/enigma2
+fi
+
+# enigma2 exit codes:
+#
+#  1 - halt
+#  2 - reboot
+#  3 - restart enigma 
+#  4 - front processor upgrade
+#  5 - install new settings
+#  7 - manufacturer reset
+# 42 - offline update
+# 43 - restart for autoinstall
+#
+# >128 signal
+
+ret=$?
+
+case $ret in
+	1)
+		/sbin/halt
+		;;
+	2)
+		/sbin/reboot
+		;;
+	4)
+		/sbin/rmmod lcd
+		/usr/sbin/fpupgrade --upgrade 2>&1 | tee /home/root/fpupgrade.log
+		sleep 1;
+		/sbin/rmmod fp
+		/sbin/modprobe fp
+		/sbin/reboot
+		;;
+	5)
+		if ! grep -q config.misc.RestartUI /etc/enigma2/settings; then
+		echo "config.misc.RestartUI=true" >>/etc/enigma2/settings
+		fi
+		;;
+	7)
+		rm -R /etc/enigma2
+		;;
+	42)
+		df -P | grep -v "tmpfs " | awk '{print $6}' | tail -n +3 > /tmp/upgrade_mountpoints.txt
+		while read line; do
+			if [  -f $line/var/lib/opkg/status ]; then
+			DESTS=$DESTS" --add-dest "$line":"$line
+		fi
+		done < /tmp/upgrade_mountpoints.txt
+		# bind the console (when available)
+		[ -f /sys/class/vtconsole/vtcon1/bind ] && echo 1 > /sys/class/vtconsole/vtcon1/bind
+		prevupd=0
+		currupd=999
+		opkg update 2>&1 | tee /home/root/opkgupgrade.log
+		# check if we need to upgrade busybox first
+		if [ "$(opkg list-upgradable busybox)" != "" ]; then
+			opkg update busybox 2>&1 | tee -a /home/root/opkgupgrade.log
+		fi
+		# update all other packages
+		while [ $currupd -gt 0 -a $currupd -ne $prevupd ]; do
+			opkg upgrade $DESTS 2>&1 | tee -a /home/root/opkgupgrade.log
+			prevupd=$currupd
+			currupd=`opkg list-upgradable | wc -l`
+			echo "===> $currupd PACKAGE(S) REMAINING" >> /home/root/opkgupgrade.log
+		done
+		/sbin/reboot
+		;;
+	43)
+		#auto install and autobackup
+		[ -f /sys/class/vtconsole/vtcon1/bind ] && echo 1 > /sys/class/vtconsole/vtcon1/bind
+		/etc/init.d/settings-restore.sh
+		/etc/init.d/avahi-daemon stop
+		ifdown eth1
+		ip addr flush dev eth1 scope global
+		ifdown eth0
+		ip addr flush dev eth0 scope global
+		/etc/init.d/networking stop
+		killall -9 udhcpc
+		rm /var/run/udhcpc*
+		/etc/init.d/dbus-1 reload
+		/etc/init.d/networking start
+		/etc/init.d/avahi-daemon start
+		/etc/init.d/softcam restart
+		# wait until we have a network again
+		echo "**** Waiting for network ****"
+		for i in {1..30}; do
+			gw=`netstat -rn | grep UG | awk '{print $2}'`
+			if [ ! -z "$gw" ]; then
+				echo "> Online !"
+				break
 			fi
-			;;
-		7)
-			rm -R /etc/enigma2
-			;;
-		42)
-			df -P | grep -v "tmpfs " | awk '{print $6}' | tail -n +3 > /tmp/upgrade_mountpoints.txt
-			while read line; do
-				if [  -f $line/var/lib/opkg/status ]; then
-				DESTS=$DESTS" --add-dest "$line":"$line
-			fi
-			done < /tmp/upgrade_mountpoints.txt
-			# bind the console (when available)
-			[ -f /sys/class/vtconsole/vtcon1/bind ] && echo 1 > /sys/class/vtconsole/vtcon1/bind
-			prevupd=0
-			currupd=999
-			opkg update 2>&1 | tee /home/root/opkgupgrade.log
-			# check if we need to upgrade busybox first
-			if [ "$(opkg list-upgradable busybox)" != "" ]; then
-				opkg update busybox 2>&1 | tee -a /home/root/opkgupgrade.log
-			fi
-			# update all other packages
-			while [ $currupd -gt 0 -a $currupd -ne $prevupd ]; do
-				opkg upgrade $DESTS 2>&1 | tee -a /home/root/opkgupgrade.log
-				prevupd=$currupd
-				currupd=`opkg list-upgradable | wc -l`
-				echo "===> $currupd PACKAGE(S) REMAINING" >> /home/root/opkgupgrade.log
-			done
-			/sbin/reboot
-			;;
-		43)
-			#auto install and autobackup
-			[ -f /sys/class/vtconsole/vtcon1/bind ] && echo 1 > /sys/class/vtconsole/vtcon1/bind
-			/etc/init.d/settings-restore.sh
-			/etc/init.d/avahi-daemon stop
-			ifdown eth1
-			ip addr flush dev eth1 scope global
-			ifdown eth0
-			ip addr flush dev eth0 scope global
-			/etc/init.d/networking stop
-			killall -9 udhcpc
-			rm /var/run/udhcpc*
-			/etc/init.d/dbus-1 reload
-			/etc/init.d/networking start
-			/etc/init.d/avahi-daemon start
-			/etc/init.d/softcam restart
-			# wait until we have a network again
-			echo "**** Waiting for network ****"
-			for i in {1..30}; do
-				gw=`netstat -rn | grep UG | awk '{print $2}'`
-				if [ ! -z "$gw" ]; then
-					echo "> Online !"
-					break
-				fi
-				sleep 1
-			done
-			break
-			;;
-		*)
-			break
-			;;
-	esac
+			sleep 1
+		done
+		break
+		;;
+	*)
+		break
+		;;
+esac
 
 done
